-- MySQL Script generated by MySQL Workbench
-- Mon Jan 20 09:53:42 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

DROP TABLE IF EXISTS `cliente`;

CREATE TABLE IF NOT EXISTS `cliente` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `Contact` BIGINT NOT NULL,
  `Direccion` TEXT NULL,
  `Email` TEXT NULL,
  PRIMARY KEY (`id`)
)
ENGINE = InnoDB;

INSERT INTO `cliente` (`name`, `Contact`, `Direccion`, `Email`) VALUES
('Ana zuleta',3104677687, 'Calle Principal 123', 'ana.garcia@example.com'),
('Pedro Lopez',3126579867, 'Avenida Central 456', 'pedro.lopez@example.com'),
('Laura Perez',3016575463, 'Calle Secundaria 789', 'laura.martinez@example.com'),
('Carlos Sanchez',3234548754, 'Avenida Norte 321', 'carlos.ramirez@example.com');
-- -----------------------------------------------------
-- Table `Fabricante`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `fabricante`;

CREATE TABLE IF NOT EXISTS `fabricante` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `Nombre_Empresa` VARCHAR(45) NOT NULL,
  `Contacto` BIGINT NOT NULL,
  `Direccion` VARCHAR(255) NOT NULL,
  `Email` VARCHAR(155) NOT NULL,
  `Calificacion` FLOAT NOT NULL,
  PRIMARY KEY (`id`)
)
ENGINE = InnoDB;
INSERT INTO `fabricante` (`Nombre_Empresa`, `Contacto`, `Direccion`, `Email`, `Calificacion`) VALUES
('Siemens Healthcare',8007436367, '123 Main Street', 'info@siemens.com', 4.5),
('Medtronic',8006338766, '456 Elm Avenue', 'contactus@medtronic.com', 4.2),
('Johnson & Johnson',8882226036, '789 Oak Road', 'contact@jnj.com', 4.8),
('General Electric Healthcare',8004371171, '321 Pine Lane', 'gehealthcare@ge.com', 4.0);


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;